-- 0020 — first drafts of the sixteen emails' wording (fifteen here; the
-- installment pair waits for the schedule table it needs).
--
-- These are DRAFTS. §2.3 puts the wording on Empiria's desk, and the console
-- under Content → Emails is where they edit it. This migration therefore
-- fills a template only where its body is still empty, and never touches one
-- Empiria has written: re-running it is safe, and so is running it after they
-- have started.
--
-- Also here: partner_application_alert, a template of its own for the staff
-- alert the partner form sends. It had reused admin_alert, whose body is about
-- a booking and needs a reference, a total and a date an application does not
-- have — with those in the body, every application alert would have failed to
-- render. Generated by scripts/email-templates/preview.ts --sql.

insert into public.email_templates (key, name, subject, body_html, body_text, is_active)
values ('partner_application_alert', 'Partner application (to Empiria)', '', '', null, true)
on conflict (key) do nothing;

with drafts(key, subject, body_html, body_text) as (values
  ('account_created', 'Confirm your email address', '<h1 style="margin:0 0 14px;font-size:26px;line-height:1.2;font-weight:700;letter-spacing:-0.01em;color:#1d2321;">Welcome, {{traveller.name}}</h1>
<p style="margin:0 0 16px;">Your account is set up with <strong>{{account.email}}</strong>. Confirm the address and you&rsquo;re in.</p>
<p style="margin:26px 0 6px;"><a href="{{account.confirm_link}}" style="display:inline-block;background:#f15a29;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;line-height:1;padding:14px 24px;border-radius:999px;">Confirm my email</a></p>
<p style="margin:24px 0 0;font-size:14px;line-height:1.55;color:#6a716d;">If you didn&rsquo;t create this account, ignore this email and nothing will happen.</p>', 'Welcome, {{traveller.name}}

Your account is set up with {{account.email}}. Confirm the address and you''re in:
{{account.confirm_link}}

If you didn''t create this account, ignore this email and nothing will happen.'),
  ('booking_confirmed', 'Your booking is confirmed — {{booking.reference}}', '<h1 style="margin:0 0 14px;font-size:26px;line-height:1.2;font-weight:700;letter-spacing:-0.01em;color:#1d2321;">Your places are confirmed</h1>
<p style="margin:0 0 16px;">Thank you, {{traveller.name}}. Your booking for <strong>{{package.title}}</strong> is confirmed, and your places are held in your name.</p>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:20px 0 22px;border-collapse:collapse;">
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Reference</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{booking.reference}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Trip</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{package.title}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Departs</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{departure.date}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Travellers</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{booking.travellers}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Meeting point</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{departure.meeting_point}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;border-bottom:1px solid #ebe4d8;">Total</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;border-bottom:1px solid #ebe4d8;">{{booking.total}}</td></tr>
</table>
<p style="margin:0 0 16px;">Keep the reference &mdash; it&rsquo;s how we find your booking whenever you get in touch. We&rsquo;ll write again before you travel with the practical details.</p>
<p style="margin:24px 0 0;font-size:14px;line-height:1.55;color:#6a716d;">Questions? Write to {{company.contact_email}} and quote {{booking.reference}}.</p>', 'Your places are confirmed

Thank you, {{traveller.name}}. Your booking for {{package.title}} is confirmed, and your places are held in your name.

Reference:     {{booking.reference}}
Trip:          {{package.title}}
Departs:       {{departure.date}}
Travellers:    {{booking.travellers}}
Meeting point: {{departure.meeting_point}}
Total:         {{booking.total}}

Keep the reference — it''s how we find your booking whenever you get in touch. We''ll write again before you travel with the practical details.

Questions? Write to {{company.contact_email}} and quote {{booking.reference}}.'),
  ('deposit_taken', 'Deposit received — {{booking.reference}}', '<h1 style="margin:0 0 14px;font-size:26px;line-height:1.2;font-weight:700;letter-spacing:-0.01em;color:#1d2321;">Deposit received</h1>
<p style="margin:0 0 16px;">Thank you, {{traveller.name}}. We&rsquo;ve received <strong>{{payment.amount}}</strong> towards your booking for <strong>{{package.title}}</strong>, and your places are held.</p>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:20px 0 22px;border-collapse:collapse;">
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Reference</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{booking.reference}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Trip</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{package.title}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Departs</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{departure.date}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Paid today</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{payment.amount}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Balance</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{booking.balance}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;border-bottom:1px solid #ebe4d8;">Balance due by</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;border-bottom:1px solid #ebe4d8;">{{booking.balance_due_on}}</td></tr>
</table>
<p style="margin:0 0 16px;">We&rsquo;ll remind you before the balance is due, with a link to pay it.</p>
<p style="margin:24px 0 0;font-size:14px;line-height:1.55;color:#6a716d;">Questions? Write to {{company.contact_email}} and quote {{booking.reference}}.</p>', 'Deposit received

Thank you, {{traveller.name}}. We''ve received {{payment.amount}} towards your booking for {{package.title}}, and your places are held.

Reference:      {{booking.reference}}
Trip:           {{package.title}}
Departs:        {{departure.date}}
Paid today:     {{payment.amount}}
Balance:        {{booking.balance}}
Balance due by: {{booking.balance_due_on}}

We''ll remind you before the balance is due, with a link to pay it.

Questions? Write to {{company.contact_email}} and quote {{booking.reference}}.'),
  ('balance_due', 'Your balance is due by {{booking.balance_due_on}} — {{booking.reference}}', '<h1 style="margin:0 0 14px;font-size:26px;line-height:1.2;font-weight:700;letter-spacing:-0.01em;color:#1d2321;">Your balance is due soon</h1>
<p style="margin:0 0 16px;">Hello {{traveller.name}}. The balance on your booking for <strong>{{package.title}}</strong> is due by <strong>{{booking.balance_due_on}}</strong>.</p>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:20px 0 22px;border-collapse:collapse;">
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Reference</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{booking.reference}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Trip</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{package.title}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Departs</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{departure.date}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Balance</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{booking.balance}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;border-bottom:1px solid #ebe4d8;">Due by</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;border-bottom:1px solid #ebe4d8;">{{booking.balance_due_on}}</td></tr>
</table>
<p style="margin:26px 0 6px;"><a href="{{payment.link}}" style="display:inline-block;background:#f15a29;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;line-height:1;padding:14px 24px;border-radius:999px;">Pay the balance</a></p>
<p style="margin:24px 0 0;font-size:14px;line-height:1.55;color:#6a716d;">Already paid? Then this crossed with your payment &mdash; thank you, and please ignore it. Questions? Write to {{company.contact_email}} and quote {{booking.reference}}.</p>', 'Your balance is due soon

Hello {{traveller.name}}. The balance on your booking for {{package.title}} is due by {{booking.balance_due_on}}.

Reference: {{booking.reference}}
Trip:      {{package.title}}
Departs:   {{departure.date}}
Balance:   {{booking.balance}}
Due by:    {{booking.balance_due_on}}

Pay the balance: {{payment.link}}

Already paid? Then this crossed with your payment — thank you, and please ignore it.
Questions? Write to {{company.contact_email}} and quote {{booking.reference}}.'),
  ('balance_paid', 'Paid in full — {{booking.reference}}', '<h1 style="margin:0 0 14px;font-size:26px;line-height:1.2;font-weight:700;letter-spacing:-0.01em;color:#1d2321;">Paid in full &mdash; thank you</h1>
<p style="margin:0 0 16px;">Hello {{traveller.name}}. We&rsquo;ve received <strong>{{payment.amount}}</strong>, and your booking for <strong>{{package.title}}</strong> is now paid in full.</p>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:20px 0 22px;border-collapse:collapse;">
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Reference</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{booking.reference}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Trip</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{package.title}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Departs</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{departure.date}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Received today</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{payment.amount}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;border-bottom:1px solid #ebe4d8;">Total paid</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;border-bottom:1px solid #ebe4d8;">{{booking.total}}</td></tr>
</table>
<p style="margin:0 0 16px;">There&rsquo;s nothing more to pay. We&rsquo;ll be in touch before you travel with the practical details.</p>
<p style="margin:24px 0 0;font-size:14px;line-height:1.55;color:#6a716d;">Questions? Write to {{company.contact_email}} and quote {{booking.reference}}.</p>', 'Paid in full — thank you

Hello {{traveller.name}}. We''ve received {{payment.amount}}, and your booking for {{package.title}} is now paid in full.

Reference:      {{booking.reference}}
Trip:           {{package.title}}
Departs:        {{departure.date}}
Received today: {{payment.amount}}
Total paid:     {{booking.total}}

There''s nothing more to pay. We''ll be in touch before you travel with the practical details.

Questions? Write to {{company.contact_email}} and quote {{booking.reference}}.'),
  ('pre_departure', 'Before you go: {{package.title}} on {{departure.date}}', '<h1 style="margin:0 0 14px;font-size:26px;line-height:1.2;font-weight:700;letter-spacing:-0.01em;color:#1d2321;">Before you go</h1>
<p style="margin:0 0 16px;">Hello {{traveller.name}}. Your trip on <strong>{{package.title}}</strong> departs on <strong>{{departure.date}}</strong>. Here&rsquo;s what you need on the day.</p>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:20px 0 22px;border-collapse:collapse;">
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Reference</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{booking.reference}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Departs</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{departure.date}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Time</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{departure.start_time}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;border-bottom:1px solid #ebe4d8;">Meeting point</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;border-bottom:1px solid #ebe4d8;">{{departure.meeting_point}}</td></tr>
</table>
<h2 style="margin:26px 0 10px;font-size:13px;line-height:1.3;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;color:#6a716d;">What to bring</h2>
<p style="margin:0 0 16px;white-space:pre-line;">{{package.what_to_bring}}</p>
<p style="margin:24px 0 0;font-size:14px;line-height:1.55;color:#6a716d;">Anything unclear? Write to {{company.contact_email}} and quote {{booking.reference}}. Have a wonderful trip.</p>', 'Before you go

Hello {{traveller.name}}. Your trip on {{package.title}} departs on {{departure.date}}. Here''s what you need on the day.

Reference:     {{booking.reference}}
Departs:       {{departure.date}}
Time:          {{departure.start_time}}
Meeting point: {{departure.meeting_point}}

WHAT TO BRING
{{package.what_to_bring}}

Anything unclear? Write to {{company.contact_email}} and quote {{booking.reference}}. Have a wonderful trip.'),
  ('booking_amended', 'Your booking has been updated — {{booking.reference}}', '<h1 style="margin:0 0 14px;font-size:26px;line-height:1.2;font-weight:700;letter-spacing:-0.01em;color:#1d2321;">Your booking has been updated</h1>
<p style="margin:0 0 16px;">Hello {{traveller.name}}. We&rsquo;ve made a change to your booking for <strong>{{package.title}}</strong>, departing {{departure.date}}.</p>
<h2 style="margin:26px 0 10px;font-size:13px;line-height:1.3;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;color:#6a716d;">What changed</h2>
<p style="margin:0 0 16px;white-space:pre-line;">{{booking.changes}}</p>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:20px 0 22px;border-collapse:collapse;">
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Reference</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{booking.reference}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Trip</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{package.title}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;border-bottom:1px solid #ebe4d8;">Departs</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;border-bottom:1px solid #ebe4d8;">{{departure.date}}</td></tr>
</table>
<p style="margin:24px 0 0;font-size:14px;line-height:1.55;color:#6a716d;">If this isn&rsquo;t what you expected, write to {{company.contact_email}} and quote {{booking.reference}}.</p>', 'Your booking has been updated

Hello {{traveller.name}}. We''ve made a change to your booking for {{package.title}}, departing {{departure.date}}.

WHAT CHANGED
{{booking.changes}}

Reference: {{booking.reference}}
Trip:      {{package.title}}
Departs:   {{departure.date}}

If this isn''t what you expected, write to {{company.contact_email}} and quote {{booking.reference}}.'),
  ('departure_change', 'Your departure date has changed — {{booking.reference}}', '<h1 style="margin:0 0 14px;font-size:26px;line-height:1.2;font-weight:700;letter-spacing:-0.01em;color:#1d2321;">Your departure date has changed</h1>
<p style="margin:0 0 16px;">Hello {{traveller.name}}. The departure for <strong>{{package.title}}</strong> has moved.</p>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:20px 0 22px;border-collapse:collapse;">
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Reference</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{booking.reference}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Was</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{departure.old_date}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Now</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{departure.date}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;border-bottom:1px solid #ebe4d8;">Why</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;border-bottom:1px solid #ebe4d8;">{{departure.reason}}</td></tr>
</table>
<p style="margin:24px 0 0;font-size:14px;line-height:1.55;color:#6a716d;">If the new date doesn&rsquo;t work for you, write to {{company.contact_email}} and quote {{booking.reference}} &mdash; we&rsquo;ll talk it through.</p>', 'Your departure date has changed

Hello {{traveller.name}}. The departure for {{package.title}} has moved.

Reference: {{booking.reference}}
Was:       {{departure.old_date}}
Now:       {{departure.date}}
Why:       {{departure.reason}}

If the new date doesn''t work for you, write to {{company.contact_email}} and quote {{booking.reference}} — we''ll talk it through.'),
  ('booking_cancelled', 'Your booking has been cancelled — {{booking.reference}}', '<h1 style="margin:0 0 14px;font-size:26px;line-height:1.2;font-weight:700;letter-spacing:-0.01em;color:#1d2321;">Your booking has been cancelled</h1>
<p style="margin:0 0 16px;">Hello {{traveller.name}}. Your booking for <strong>{{package.title}}</strong>, departing {{departure.date}}, has been cancelled.</p>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:20px 0 22px;border-collapse:collapse;">
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Reference</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{booking.reference}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Trip</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{package.title}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Departure</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{departure.date}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;border-bottom:1px solid #ebe4d8;">Refund due</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;border-bottom:1px solid #ebe4d8;">{{booking.refund_due}}</td></tr>
</table>
<p style="margin:0 0 16px;">Any refund shown above goes back to the original payment method, and we&rsquo;ll email you when it&rsquo;s sent.</p>
<p style="margin:24px 0 0;font-size:14px;line-height:1.55;color:#6a716d;">Questions? Write to {{company.contact_email}} and quote {{booking.reference}}.</p>', 'Your booking has been cancelled

Hello {{traveller.name}}. Your booking for {{package.title}}, departing {{departure.date}}, has been cancelled.

Reference:  {{booking.reference}}
Trip:       {{package.title}}
Departure:  {{departure.date}}
Refund due: {{booking.refund_due}}

Any refund shown above goes back to the original payment method, and we''ll email you when it''s sent.

Questions? Write to {{company.contact_email}} and quote {{booking.reference}}.'),
  ('refund_issued', 'Your refund is on its way — {{booking.reference}}', '<h1 style="margin:0 0 14px;font-size:26px;line-height:1.2;font-weight:700;letter-spacing:-0.01em;color:#1d2321;">Your refund is on its way</h1>
<p style="margin:0 0 16px;">Hello {{traveller.name}}. We&rsquo;ve sent a refund of <strong>{{payment.amount}}</strong> for your booking for <strong>{{package.title}}</strong>.</p>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:20px 0 22px;border-collapse:collapse;">
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Reference</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{booking.reference}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Trip</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{package.title}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Amount</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{payment.amount}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;border-bottom:1px solid #ebe4d8;">Sent to</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;border-bottom:1px solid #ebe4d8;">{{payment.method}}</td></tr>
</table>
<p style="margin:0 0 16px;">It can take a few business days to appear, depending on your bank.</p>
<p style="margin:24px 0 0;font-size:14px;line-height:1.55;color:#6a716d;">Questions? Write to {{company.contact_email}} and quote {{booking.reference}}.</p>', 'Your refund is on its way

Hello {{traveller.name}}. We''ve sent a refund of {{payment.amount}} for your booking for {{package.title}}.

Reference: {{booking.reference}}
Trip:      {{package.title}}
Amount:    {{payment.amount}}
Sent to:   {{payment.method}}

It can take a few business days to appear, depending on your bank.

Questions? Write to {{company.contact_email}} and quote {{booking.reference}}.'),
  ('admin_alert', 'New booking {{booking.reference}}: {{package.title}}', '<h1 style="margin:0 0 14px;font-size:26px;line-height:1.2;font-weight:700;letter-spacing:-0.01em;color:#1d2321;">New booking</h1>
<p style="margin:0 0 16px;"><strong>{{traveller.name}}</strong> has booked <strong>{{package.title}}</strong>, departing {{departure.date}}.</p>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:20px 0 22px;border-collapse:collapse;">
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Reference</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{booking.reference}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Traveller</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{traveller.name}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Trip</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{package.title}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;">Departs</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;">{{departure.date}}</td></tr>
<tr><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-size:13px;color:#6a716d;width:36%;padding-right:16px;border-bottom:1px solid #ebe4d8;">Total</td><td style="padding:11px 0;border-top:1px solid #ebe4d8;vertical-align:top;font-weight:600;border-bottom:1px solid #ebe4d8;">{{booking.total}}</td></tr>
</table>
<p style="margin:26px 0 6px;"><a href="{{booking.admin_link}}" style="display:inline-block;background:#f15a29;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;line-height:1;padding:14px 24px;border-radius:999px;">Open in the console</a></p>', 'New booking

{{traveller.name}} has booked {{package.title}}, departing {{departure.date}}.

Reference: {{booking.reference}}
Traveller: {{traveller.name}}
Trip:      {{package.title}}
Departs:   {{departure.date}}
Total:     {{booking.total}}

Open in the console: {{booking.admin_link}}'),
  ('partner_application_received', 'We have your application', '<h1 style="margin:0 0 14px;font-size:26px;line-height:1.2;font-weight:700;letter-spacing:-0.01em;color:#1d2321;">Thanks &mdash; we have your application</h1>
<p style="margin:0 0 16px;">Hello {{applicant.name}}. Your application for <strong>{{applicant.company}}</strong> to sell tours through Empiria Tours has arrived.</p>
<p style="margin:0 0 16px;">A person at Empiria reads every application &mdash; nothing here is approved automatically. We&rsquo;ll email you once it&rsquo;s been reviewed.</p>
<p style="margin:24px 0 0;font-size:14px;line-height:1.55;color:#6a716d;">Questions? Write to {{company.contact_email}}.</p>', 'Thanks — we have your application

Hello {{applicant.name}}. Your application for {{applicant.company}} to sell tours through Empiria Tours has arrived.

A person at Empiria reads every application — nothing here is approved automatically. We''ll email you once it''s been reviewed.

Questions? Write to {{company.contact_email}}.'),
  ('partner_application_approved', 'Welcome aboard, {{applicant.company}}', '<h1 style="margin:0 0 14px;font-size:26px;line-height:1.2;font-weight:700;letter-spacing:-0.01em;color:#1d2321;">Welcome aboard</h1>
<p style="margin:0 0 16px;">Hello {{applicant.name}}. Your application for <strong>{{applicant.company}}</strong> has been approved, and your partner console is ready.</p>
<p style="margin:0 0 16px;">You&rsquo;ll receive a separate email to set up your sign-in. Once you&rsquo;re in, you can add your tours, set departures and see bookings as they come.</p>
<p style="margin:26px 0 6px;"><a href="{{partner.console_link}}" style="display:inline-block;background:#f15a29;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;line-height:1;padding:14px 24px;border-radius:999px;">Open the partner console</a></p>
<p style="margin:24px 0 0;font-size:14px;line-height:1.55;color:#6a716d;">Questions? Write to {{company.contact_email}}.</p>', 'Welcome aboard

Hello {{applicant.name}}. Your application for {{applicant.company}} has been approved, and your partner console is ready.

You''ll receive a separate email to set up your sign-in. Once you''re in, you can add your tours, set departures and see bookings as they come.

Open the partner console: {{partner.console_link}}

Questions? Write to {{company.contact_email}}.'),
  ('partner_application_declined', 'About your application', '<h1 style="margin:0 0 14px;font-size:26px;line-height:1.2;font-weight:700;letter-spacing:-0.01em;color:#1d2321;">About your application</h1>
<p style="margin:0 0 16px;">Hello {{applicant.name}}. Thank you for applying for <strong>{{applicant.company}}</strong> to sell tours through Empiria Tours. We&rsquo;ve reviewed it and won&rsquo;t be going ahead this time.</p>
<h2 style="margin:26px 0 10px;font-size:13px;line-height:1.3;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;color:#6a716d;">A note from the reviewer</h2>
<p style="margin:0 0 16px;white-space:pre-line;">{{application.note}}</p>
<p style="margin:24px 0 0;font-size:14px;line-height:1.55;color:#6a716d;">If you&rsquo;d like to talk it through, write to {{company.contact_email}}.</p>', 'About your application

Hello {{applicant.name}}. Thank you for applying for {{applicant.company}} to sell tours through Empiria Tours. We''ve reviewed it and won''t be going ahead this time.

A NOTE FROM THE REVIEWER
{{application.note}}

If you''d like to talk it through, write to {{company.contact_email}}.'),
  ('partner_application_alert', 'New partner application: {{applicant.company}}', '<h1 style="margin:0 0 14px;font-size:26px;line-height:1.2;font-weight:700;letter-spacing:-0.01em;color:#1d2321;">New partner application</h1>
<p style="margin:0 0 16px;"><strong>{{applicant.name}}</strong> has applied on behalf of <strong>{{applicant.company}}</strong>.</p>
<p style="margin:26px 0 6px;"><a href="{{application.admin_link}}" style="display:inline-block;background:#f15a29;color:#ffffff;text-decoration:none;font-weight:600;font-size:15px;line-height:1;padding:14px 24px;border-radius:999px;">Review the application</a></p>', 'New partner application

{{applicant.name}} has applied on behalf of {{applicant.company}}.

Review the application: {{application.admin_link}}')
)
update public.email_templates t
   set subject   = d.subject,
       body_html = d.body_html,
       body_text = d.body_text,
       updated_at = now()
  from drafts d
 where t.key = d.key
   and coalesce(t.body_html, '') = '';

do $$
declare
  v_empty int;
  v_names text;
begin
  select count(*), coalesce(string_agg(key, ', '), '') into v_empty, v_names
    from public.email_templates
   where coalesce(body_html, '') = ''
     and key not in ('installment_due', 'installment_paid');
  if v_empty > 0 then
    raise exception '0020: % template(s) still empty: %', v_empty, v_names;
  end if;
  raise notice '0020: every template that can send has a body';
end $$;
