/**
 * Render every draft through the real renderer and frame, with sample facts.
 *
 *   bun run scripts/email-templates/preview.ts          → /tmp/empiria-email/<key>.html
 *   bun run scripts/email-templates/preview.ts --sql    → the migration, on stdout
 *
 * The render is the check: the renderer throws on a field a template may not
 * use or a value the sample forgot, so a draft that renders here is a draft
 * that will render for a real booking. The console has no preview of its own
 * yet; until it does, this is how a template is looked at.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { renderEmail, TemplateError } from '../../lib/email/render.ts';
import { wrapEmail } from '../../lib/email/layout.ts';
import { TEMPLATE_FIELDS } from '../../lib/email/fields.ts';
import { DRAFTS } from './drafts.ts';

const sql = process.argv.includes('--sql');
const OUT = '/tmp/empiria-email';

const brand = {
  companyName: 'Empiria World Inc.',
  registrationNumber: '50012345',
  contactEmail: 'info@empiria.tours',
  // The preview reads the logo straight off disk; production uses TOUR_URL.
  logoUrl: `file://${resolve(import.meta.dirname, '../../public/logo.png')}`,
  siteUrl: 'https://tour.empiria.events',
};
const company = {
  'company.name': brand.companyName,
  'company.registration_number': brand.registrationNumber,
  'company.contact_email': brand.contactEmail,
};

const sqlLit = (s: string) => `'${s.replace(/'/g, "''")}'`;

if (sql) {
  const rows = Object.entries(DRAFTS)
    .map(
      ([key, d]) =>
        `  (${sqlLit(key)}, ${sqlLit(d.subject)}, ${sqlLit(d.html)}, ${sqlLit(d.text)})`
    )
    .join(',\n');
  process.stdout.write(`-- 0020 — first drafts of the sixteen emails' wording (fifteen here; the
-- installment pair waits for the schedule table it needs).
--
-- These are DRAFTS. §2.3 puts the wording on Empiria's desk, and the console
-- under Content → Emails is where they edit it. This migration therefore
-- fills a template only where its body is still empty, and never touches one
-- Empiria has written: re-running it is safe, and so is running it after they
-- have started.
--
-- Also here: partner_application_alert, a template of its own for the staff
-- alert the partner form sends. It had reused admin_alert, whose body is about
-- a booking and needs a reference, a total and a date an application does not
-- have — with those in the body, every application alert would have failed to
-- render. Generated by scripts/email-templates/preview.ts --sql.

insert into public.email_templates (key, name, subject, body_html, body_text, is_active)
values ('partner_application_alert', 'Partner application (to Empiria)', '', '', null, true)
on conflict (key) do nothing;

with drafts(key, subject, body_html, body_text) as (values
${rows}
)
update public.email_templates t
   set subject   = d.subject,
       body_html = d.body_html,
       body_text = d.body_text,
       updated_at = now()
  from drafts d
 where t.key = d.key
   and coalesce(t.body_html, '') = '';

do $$
declare
  v_empty int;
  v_names text;
begin
  select count(*), coalesce(string_agg(key, ', '), '') into v_empty, v_names
    from public.email_templates
   where coalesce(body_html, '') = ''
     and key not in ('installment_due', 'installment_paid');
  if v_empty > 0 then
    raise exception '0020: % template(s) still empty: %', v_empty, v_names;
  end if;
  raise notice '0020: every template that can send has a body';
end $$;
`);
  process.exit(0);
}

mkdirSync(OUT, { recursive: true });
let failed = 0;
const undrafted = Object.keys(TEMPLATE_FIELDS).filter((k) => !DRAFTS[k]);
for (const [key, d] of Object.entries(DRAFTS)) {
  try {
    const rendered = renderEmail(
      { key, subject: d.subject, body_html: d.html, body_text: d.text },
      { ...d.sample, ...company }
    );
    const wrapped = wrapEmail(rendered, brand);
    writeFileSync(`${OUT}/${key}.html`, wrapped.html);
    writeFileSync(`${OUT}/${key}.txt`, `Subject: ${rendered.subject}\n\n${wrapped.text ?? ''}`);
    console.log(`ok    ${key.padEnd(30)} ${rendered.subject}`);
  } catch (e) {
    failed++;
    console.log(`FAIL  ${key.padEnd(30)} ${e instanceof TemplateError ? e.message : String(e)}`);
  }
}
console.log(`\n${Object.keys(DRAFTS).length - failed} rendered, ${failed} failed → ${OUT}/`);
if (undrafted.length) console.log(`no draft (by design): ${undrafted.join(', ')}`);
process.exit(failed ? 1 : 0);
